import { RackType, Equipment } from './types';

// PDUモデルをエクスポート
export * from './constants/pduModels';

// 基本サイズ定義
export const BASE_UNIT_HEIGHT = 32; // 1ユニットの基本高さ (px)
export const BASE_FONT_SIZE = 12; // 基本フォントサイズ (px)
export const BASE_MARGIN_LEFT = 24; // U番号の基本左マージン (px)
export const BASE_CAGE_NUT_SIZE = 16; // ケージナットの基本サイズ (px)
// ラック種類ライブラリ
export const rackTypes: Record<string, RackType> = {
  '42u-standard': { 
    name: '42U 標準ラック', 
    units: 42, 
    depth: 1000, 
    width: 600, 
    maxWeight: 1500, 
    price: 150000, 
    description: '最も一般的なサーバーラック。幅600mm、奥行1000mmで多くの機器に対応' 
  },
  '42u-deep': { 
    name: '42U 深型ラック', 
    units: 42, 
    depth: 1200, 
    width: 600, 
    maxWeight: 1800, 
    price: 180000, 
    description: '深い機器や大型ストレージ用。奥行1200mmで余裕のあるケーブル配線が可能' 
  },
  '45u-standard': { 
    name: '45U 標準ラック', 
    units: 45, 
    depth: 1000, 
    width: 600, 
    maxWeight: 1600, 
    price: 170000, 
    description: '高密度配置用の高いラック。天井高に余裕がある場合に選択' 
  },
  '36u-compact': { 
    name: '36U コンパクト', 
    units: 36, 
    depth: 800, 
    width: 600, 
    maxWeight: 1200, 
    price: 120000, 
    description: '小規模環境や低天井環境用。コンパクトながら必要十分な容量' 
  },
  '42u-wide': { 
    name: '42U ワイド', 
    units: 42, 
    depth: 1000, 
    width: 800, 
    maxWeight: 1500, 
    price: 200000, 
    description: '幅広機器や特殊用途向け。通常より200mm幅が広い特殊ラック' 
  },
  '24u-wall': { 
    name: '24U 壁掛け', 
    units: 24, 
    depth: 600, 
    width: 600, 
    maxWeight: 800, 
    price: 80000, 
    description: '壁面設置用の小型ラック。軽量機器や小規模環境向け' 
  },
};

// 機器ライブラリ（サーバー類）
export const serverEquipment: Equipment[] = [
  {
    id: 'server-1u',
    name: 'ラックマウントサーバー (1U)',
    height: 1,
    depth: 650,
    power: 300,
    heat: 1024,
    weight: 15,
    type: 'server',
    role: 'compute',
    color: '#7943a8',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 65,
    heatGeneration: 1024,
    healthStatus: 'normal',
    description: '汎用的な1Uラックマウントサーバー。Webサーバーやアプリケーションサーバーとして広く使用される。前面から背面へのエアフローで効率的な冷却を実現。',
    specifications: {
      cpu: '最大2ソケット',
      memory: '最大512GB',
      storage: '2.5インチ×4台',
      network: 'Gigabit×2, 10GbE対応',
      powerSupply: '冗長電源対応'
    },
    mountingNotes: 'スライドレール必須。ケーブルアーム推奨。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false,
    availableSizes: [
      {
        height: 1,
        power: 300,
        heat: 1024,
        weight: 15,
        cfm: 65,
        heatGeneration: 1024,
        specifications: {
          cpu: '最大2ソケット',
          memory: '最大512GB',
          storage: '2.5インチ×4台',
          network: 'Gigabit×2, 10GbE対応',
          powerSupply: '冗長電源対応'
        }
      },
      {
        height: 2,
        power: 600,
        heat: 2048,
        weight: 28,
        cfm: 120,
        heatGeneration: 2048,
        specifications: {
          cpu: '最大4ソケット',
          memory: '最大1TB',
          storage: '2.5インチ×8台',
          network: 'Gigabit×4, 10GbE×2対応',
          powerSupply: '冗長電源対応'
        }
      },
      {
        height: 4,
        power: 1200,
        heat: 4096,
        weight: 55,
        cfm: 240,
        heatGeneration: 4096,
        specifications: {
          cpu: '最大8ソケット',
          memory: '最大2TB',
          storage: '2.5インチ×16台',
          network: 'Gigabit×8, 10GbE×4対応',
          powerSupply: '冗長電源対応'
        }
      }
    ],
    selectedSize: 1
  },
  {
    id: 'server-2u',
    name: 'ラックマウントサーバー (2U)',
    height: 2,
    depth: 650,
    power: 600,
    heat: 2048,
    weight: 28,
    type: 'server',
    role: 'compute',
    color: '#7943a8',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 120,
    heatGeneration: 2048,
    healthStatus: 'normal',
    description: '高性能2Uラックマウントサーバー。データベースサーバーや仮想化基盤として使用される。拡張性と冷却性能を重視した設計。',
    specifications: {
      cpu: '最大4ソケット',
      memory: '最大1TB',
      storage: '2.5インチ×8台',
      network: 'Gigabit×4, 10GbE×2対応',
      powerSupply: '冗長電源対応'
    },
    mountingNotes: 'スライドレール必須。重量のため2人作業推奨。ケーブルアーム推奨。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'server-4u',
    name: 'ラックマウントサーバー (4U)',
    height: 4,
    depth: 650,
    power: 1200,
    heat: 4096,
    weight: 55,
    type: 'server',
    role: 'compute',
    color: '#7943a8',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 240,
    heatGeneration: 4096,
    healthStatus: 'normal',
    description: '最高性能4Uラックマウントサーバー。ミッションクリティカルなアプリケーションや大規模仮想化環境向け。最大拡張性と冗長性を提供。',
    specifications: {
      cpu: '最大8ソケット',
      memory: '最大2TB',
      storage: '2.5インチ×16台',
      network: 'Gigabit×8, 10GbE×4対応',
      powerSupply: '冗長電源対応'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。専用ケーブルアーム推奨。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'blade-server-10u',
    name: 'ブレードサーバー (10U)',
    height: 10,
    depth: 700,
    power: 3000,
    heat: 10240,
    weight: 120,
    type: 'server',
    role: 'compute',
    color: '#7943a8',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 800,
    heatGeneration: 10240,
    healthStatus: 'normal',
    description: '10Uブレードサーバーシャーシ。最大16枚のブレードサーバーを収容可能。高密度仮想化環境やクラウド基盤向け。',
    specifications: {
      blades: '最大16枚のブレードサーバー',
      cpu: 'ブレード当たり最大2ソケット',
      memory: 'ブレード当たり最大1TB',
      network: '10GbE/25GbE/40GbE対応',
      management: '統合管理モジュール',
      powerSupply: '冗長電源×6基',
      cooling: '冗長ファンモジュール×8基'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。専用ケーブルアーム推奨。十分な電源容量確保必要。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  }
];

// ネットワーク機器
export const networkEquipment: Equipment[] = [
  {
    id: 'switch-1u',
    name: 'ネットワークスイッチ (1U)',
    height: 1,
    depth: 400,
    power: 150,
    heat: 512,
    weight: 8,
    type: 'network',
    role: 'network',
    color: '#1E40AF',
    opacity: 30,
    dualPower: true,
    airflow: 'side-to-side',
    cfm: 45,
    heatGeneration: 512,
    healthStatus: 'normal',
    description: '1Uアクセススイッチ。24-48ポートのGigabitEthernetを提供。小規模から中規模ネットワーク向け。',
    specifications: {
      ports: 'Gigabit×24-48',
      uplink: '10GbE×4',
      stackable: '最大8台',
      power: 'PoE+対応',
      management: 'Web/CLI/SNMP'
    },
    mountingNotes: 'ケージナット固定。前面アクセス要確保。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'switch-2u',
    name: 'ネットワークスイッチ (2U)',
    height: 2,
    depth: 450,
    power: 300,
    heat: 1024,
    weight: 18,
    type: 'network',
    role: 'network',
    color: '#1E40AF',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 90,
    heatGeneration: 1024,
    healthStatus: 'normal',
    description: '2U高密度スイッチ。48-96ポートのGigabitEthernet + 高速アップリンクを提供。大規模ネットワーク向け。',
    specifications: {
      ports: 'Gigabit×48-96',
      uplink: '10GbE×8, 40GbE×4',
      stackable: '最大16台',
      power: 'PoE++対応',
      management: 'Web/CLI/SNMP/NETCONF'
    },
    mountingNotes: 'スライドレール必須。重量のため2人作業推奨。前面・背面アクセス要確保。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'switch-4u',
    name: 'ネットワークスイッチ (4U)',
    height: 4,
    depth: 500,
    power: 600,
    heat: 2048,
    weight: 35,
    type: 'network',
    role: 'network',
    color: '#1E40AF',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 180,
    heatGeneration: 2048,
    healthStatus: 'normal',
    description: '4Uモジュラースイッチ。最大384ポートのGigabitEthernet + 超高速アップリンクを提供。データセンター向け。',
    specifications: {
      ports: 'Gigabit×192-384',
      uplink: '10GbE×16, 40GbE×8, 100GbE×4',
      stackable: 'VSS/VPC対応',
      power: 'PoE++対応',
      management: 'Web/CLI/SNMP/NETCONF/RESTCONF'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。専用ケーブルアーム推奨。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'firewall-1u',
    name: 'ファイアウォール (1U)',
    height: 1,
    depth: 400,
    power: 180,
    heat: 614,
    weight: 10,
    type: 'security',
    role: 'security',
    color: '#DC2626',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 55,
    heatGeneration: 614,
    healthStatus: 'normal',
    description: '1U次世代ファイアウォール。アプリケーション制御、IPS、アンチウイルス機能を統合。中小規模向け。',
    specifications: {
      throughput: '最大5Gbps',
      rules: '最大10万ルール',
      features: 'IPS/AV/URL filtering',
      vpn: 'SSL-VPN/IPsec対応',
      management: '統合管理コンソール'
    },
    mountingNotes: 'ケージナット固定。セキュリティ機器につき物理アクセス制限要検討。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'firewall-2u',
    name: 'ファイアウォール (2U)',
    height: 2,
    depth: 450,
    power: 350,
    heat: 1195,
    weight: 20,
    type: 'security',
    role: 'security',
    color: '#DC2626',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 110,
    heatGeneration: 1195,
    healthStatus: 'normal',
    description: '2U高性能次世代ファイアウォール。高スループット処理とアドバンスドセキュリティ機能を提供。大規模企業向け。',
    specifications: {
      throughput: '最大20Gbps',
      rules: '最大50万ルール',
      features: 'IPS/AV/URL filtering/Sandboxing',
      vpn: 'SSL-VPN/IPsec/SD-WAN対応',
      management: '統合管理コンソール/API'
    },
    mountingNotes: 'スライドレール必須。重量のため2人作業推奨。セキュリティ機器につき物理アクセス制限要検討。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'load-balancer-1u',
    name: 'ロードバランサー (1U)',
    height: 1,
    depth: 450,
    power: 200,
    heat: 683,
    weight: 12,
    type: 'network',
    role: 'network',
    color: '#1E40AF',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 60,
    heatGeneration: 683,
    healthStatus: 'normal',
    description: '1U F5 BIG-IP アプリケーション配信コントローラ。高度な負荷分散、SSL処理、アプリケーションファイアウォール機能を統合。中規模向け。',
    specifications: {
      throughput: '最大40Gbps',
      connections: '最大800万同時接続',
      algorithms: 'Round Robin/Least Connections/Ratio/Priority/Fastest/Observed',
      healthcheck: 'L3/L4/L7ヘルスチェック + カスタムモニタ',
      ssl: 'SSL終端・オフロード・フルプロキシ対応',
      management: 'TMSH/WebUI/iControl REST API',
      features: 'iRules/ASM/APM/GTM対応',
      platform: 'TMOS OS搭載'
    },
    mountingNotes: 'ケージナット固定。冗長構成必須。管理・データネットワーク分離推奨。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'load-balancer-2u',
    name: 'ロードバランサー (2U)',
    height: 2,
    depth: 500,
    power: 400,
    heat: 1365,
    weight: 25,
    type: 'network',
    role: 'network',
    color: '#1E40AF',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 120,
    heatGeneration: 1365,
    healthStatus: 'normal',
    description: '2U F5 BIG-IP 高性能アプリケーション配信コントローラ。超高スループット処理とエンタープライズ機能を提供。大規模向け。',
    specifications: {
      throughput: '最大100Gbps',
      connections: '最大2000万同時接続',
      algorithms: 'Round Robin/Least Connections/Ratio/Priority/Fastest/Observed/Dynamic Ratio',
      healthcheck: 'L3/L4/L7ヘルスチェック + カスタムモニタ + AI分析',
      ssl: 'SSL終端・オフロード・フルプロキシ・HSM対応',
      management: 'TMSH/WebUI/iControl REST API/Ansible',
      features: 'iRules/ASM/APM/GTM/DNS/GSLB対応',
      platform: 'TMOS OS搭載'
    },
    mountingNotes: 'スライドレール必須。重量のため2人作業推奨。冗長構成必須。管理・データネットワーク分離推奨。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'core-switch-6u',
    name: '基幹スイッチ (6U)',
    height: 6,
    depth: 600,
    power: 1500,
    heat: 5120,
    weight: 80,
    type: 'network',
    role: 'network',
    color: '#1E40AF',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 450,
    heatGeneration: 5120,
    healthStatus: 'normal',
    description: '6U基幹スイッチ。データセンターのコア層を担う高性能スイッチ。超高速スループットと高可用性を提供。',
    specifications: {
      ports: '最大576ポート（モジュラー構成）',
      throughput: '最大25.6Tbps',
      uplink: '100GbE×32, 400GbE×16対応',
      protocols: 'BGP/OSPF/ISIS/MPLS/VXLAN',
      redundancy: 'シャーシ冗長化対応',
      management: 'CLI/NETCONF/RESTCONF/gNMI',
      features: 'SDN/OpenFlow対応'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。専用ケーブルアーム推奨。十分な電源容量確保必要。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'core-switch-14u',
    name: '基幹スイッチ (14U)',
    height: 14,
    depth: 650,
    power: 3500,
    heat: 11946,
    weight: 150,
    type: 'network',
    role: 'network',
    color: '#1E40AF',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 1200,
    heatGeneration: 11946,
    healthStatus: 'normal',
    description: '14U大型基幹スイッチ。Cisco Catalyst 6509相当。データセンターのコア・ディストリビューション層を担う超高性能モジュラースイッチ。',
    specifications: {
      chassis: 'Catalyst 6509相当シャーシ',
      slots: '最大9スロット（スーパーバイザー×2、ラインカード×7）',
      throughput: '最大720Gbps',
      ports: '最大576ポート（モジュラー構成）',
      uplink: '10GbE/40GbE/100GbE対応',
      protocols: 'BGP/OSPF/ISIS/MPLS/VXLAN/EVPN',
      redundancy: 'デュアルスーパーバイザー、冗長電源',
      management: 'IOS/CLI/NETCONF/RESTCONF',
      features: 'VSS/StackWise Virtual対応'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。専用ケーブルアーム推奨。十分な電源容量確保必要。床荷重確認必要。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'core-switch-21u',
    name: '基幹スイッチ (21U)',
    height: 21,
    depth: 700,
    power: 6000,
    heat: 20480,
    weight: 250,
    type: 'network',
    role: 'network',
    color: '#1E40AF',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 2000,
    heatGeneration: 20480,
    healthStatus: 'normal',
    description: '21U超大型基幹スイッチ。データセンター向け最大級のモジュラースイッチ。超高密度ポート実装と最高性能を提供。',
    specifications: {
      chassis: '超大型モジュラーシャーシ',
      slots: '最大16スロット（スーパーバイザー×2、ラインカード×14）',
      throughput: '最大51.2Tbps',
      ports: '最大1152ポート（モジュラー構成）',
      uplink: '100GbE/400GbE/800GbE対応',
      protocols: 'BGP/OSPF/ISIS/MPLS/VXLAN/EVPN/Segment Routing',
      redundancy: 'デュアルスーパーバイザー、N+1冗長電源×4',
      management: 'IOS-XR/CLI/NETCONF/RESTCONF/gNMI',
      features: 'SDN/OpenFlow/P4対応'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。専用ケーブルアーム推奨。十分な電源容量確保必要。床荷重確認必要。専用冷却計画必要。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'load-balancer',
    name: 'ロードバランサー',
    height: 1,
    depth: 450,
    power: 200,
    heat: 683,
    weight: 12,
    type: 'network',
    role: 'network',
    color: '#1E40AF',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 60,
    heatGeneration: 683,
    healthStatus: 'normal',
    description: 'アプリケーション配信コントローラ。高度な負荷分散、SSL処理機能を統合。',
    specifications: {
      throughput: '最大10Gbps',
      connections: '最大100万同時接続',
      ssl: 'SSL終端・オフロード対応'
    },
    mountingNotes: 'レール不要で簡単設置。冗長構成推奨。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'fc-switch-1u',
    name: 'Fibre Channel Switch',
    height: 1,
    depth: 610,
    power: 350,
    heat: 1194,
    weight: 8,
    type: 'network',
    role: 'network',
    color: '#c0a0e0',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 120,
    heatGeneration: 1194,
    healthStatus: 'normal',
    description: 'A high-performance Fibre Channel switch for Storage Area Networks (SAN).',
    specifications: {
      ports: '32',
      speed: '32Gb/s',
      protocol: 'Fibre Channel'
    },
    mountingNotes: 'スライドレール必須。ケージナット取り付け。SAN環境での高速ストレージ接続用。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: true
  }
];

// ストレージ機器
export const storageEquipment: Equipment[] = [
  {
    id: 'storage-1u',
    name: 'ストレージアレイ (1U)',
    height: 1,
    depth: 600,
    power: 150,
    heat: 512,
    weight: 15,
    type: 'storage',
    role: 'storage',
    color: '#059669',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 45,
    heatGeneration: 512,
    healthStatus: 'normal',
    description: '1Uストレージアレイ。小規模から中規模向け。SSD/HDD対応。',
    specifications: {
      capacity: '最大24TB',
      protocols: 'iSCSI/NFS/CIFS',
      network: '10GbE×2',
      management: 'Web管理画面'
    },
    mountingNotes: 'スライドレール必須。前面アクセス要確保。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'storage-2u',
    name: 'ストレージアレイ (2U)',
    height: 2,
    depth: 650,
    power: 300,
    heat: 1024,
    weight: 28,
    type: 'storage',
    role: 'storage',
    color: '#059669',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 90,
    heatGeneration: 1024,
    healthStatus: 'normal',
    description: '2Uストレージアレイ。中規模から大規模向け。高性能SSD/HDD対応。',
    specifications: {
      capacity: '最大96TB',
      protocols: 'iSCSI/NFS/CIFS/FC',
      network: '10GbE×4, FC×2',
      management: 'Web管理画面/CLI'
    },
    mountingNotes: 'スライドレール必須。重量のため2人作業推奨。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'storage-3u',
    name: 'ストレージアレイ (3U)',
    height: 3,
    depth: 700,
    power: 450,
    heat: 1536,
    weight: 42,
    type: 'storage',
    role: 'storage',
    color: '#059669',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 135,
    heatGeneration: 1536,
    healthStatus: 'normal',
    description: '3Uストレージアレイ。大規模向け。オールフラッシュ対応。',
    specifications: {
      capacity: '最大200TB',
      protocols: 'iSCSI/NFS/CIFS/FC/NVMe-oF',
      network: '25GbE×4, FC×4',
      management: 'Web管理画面/CLI/REST API'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業推奨。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'storage-4u',
    name: 'ストレージアレイ (4U)',
    height: 4,
    depth: 750,
    power: 600,
    heat: 2048,
    weight: 55,
    type: 'storage',
    role: 'storage',
    color: '#059669',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 180,
    heatGeneration: 2048,
    healthStatus: 'normal',
    description: '4Uストレージアレイ。エンタープライズ向け。高性能・高可用性。',
    specifications: {
      capacity: '最大500TB',
      protocols: 'iSCSI/NFS/CIFS/FC/NVMe-oF',
      network: '25GbE×8, FC×8',
      management: 'Web管理画面/CLI/REST API'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'storage-6u',
    name: 'ストレージアレイ (6U)',
    height: 6,
    depth: 800,
    power: 900,
    heat: 3072,
    weight: 80,
    type: 'storage',
    role: 'storage',
    color: '#059669',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 270,
    heatGeneration: 3072,
    healthStatus: 'normal',
    description: '6Uストレージアレイ。大規模エンタープライズ向け。最高性能・可用性。',
    specifications: {
      capacity: '最大1PB',
      protocols: 'iSCSI/NFS/CIFS/FC/NVMe-oF',
      network: '100GbE×4, FC×16',
      management: 'Web管理画面/CLI/REST API'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。床荷重確認必要。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'lto-library-2u',
    name: 'LTOテープライブラリ (2U)',
    height: 2,
    depth: 650,
    power: 180,
    heat: 614,
    weight: 30,
    type: 'storage',
    role: 'storage',
    color: '#059669',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 55,
    heatGeneration: 614,
    healthStatus: 'normal',
    description: '2U LTOテープライブラリ。自動バックアップとアーカイブ用。長期保存に最適。',
    specifications: {
      capacity: 'LTO-9×24本（432TB）',
      interface: 'SAS-3/FC対応',
      throughput: '最大400MB/s',
      automation: 'ロボットアーム自動交換',
      management: 'Web管理画面/CLI'
    },
    mountingNotes: 'スライドレール必須。重量のため2人作業推奨。前面アクセス要確保。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'lto-library-4u',
    name: 'LTOテープライブラリ (4U)',
    height: 4,
    depth: 700,
    power: 350,
    heat: 1195,
    weight: 60,
    type: 'storage',
    role: 'storage',
    color: '#059669',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 110,
    heatGeneration: 1195,
    healthStatus: 'normal',
    description: '4U LTOテープライブラリ。大容量バックアップとアーカイブ用。エンタープライズ向け。',
    specifications: {
      capacity: 'LTO-9×48本（864TB）',
      interface: 'SAS-3/FC対応',
      throughput: '最大800MB/s',
      automation: 'デュアルロボットアーム',
      management: 'Web管理画面/CLI/SNMP'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。前面アクセス要確保。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'lto-library-6u',
    name: 'LTOテープライブラリ (6U)',
    height: 6,
    depth: 750,
    power: 500,
    heat: 1707,
    weight: 90,
    type: 'storage',
    role: 'storage',
    color: '#059669',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 150,
    heatGeneration: 1707,
    healthStatus: 'normal',
    description: '6U LTOテープライブラリ。超大容量バックアップとアーカイブ用。データセンター向け。',
    specifications: {
      capacity: 'LTO-9×96本（1.7PB）',
      interface: 'SAS-3/FC対応',
      throughput: '最大1.2GB/s',
      automation: 'デュアルロボットアーム×2',
      management: 'Web管理画面/CLI/SNMP/REST API'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。前面アクセス要確保。床荷重確認必要。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  }
];

// 電源機器
export const powerEquipment: Equipment[] = [
  {
    id: 'ups-1u',
    name: 'ラックマウントUPS (1U)',
    height: 1,
    depth: 600,
    power: 50,
    heat: 171,
    weight: 45,
    type: 'ups',
    role: 'power-source',
    color: '#EA580C',
    opacity: 30,
    dualPower: false,
    airflow: 'front-to-rear',
    cfm: 80,
    heatGeneration: 171,
    description: '1U無停電電源装置。停電時の電力供給とサージ保護を提供。小規模から中規模機器向け。Smart-UPS相当。',
    specifications: {
      capacity: '3000VA/2700W',
      runtime: '約10分（フル負荷時）',
      outlets: 'C13×6, C19×2',
      input: '単相100V 15A',
      battery: 'シールド型鉛蓄電池',
      management: 'ネットワーク管理カード対応',
      protection: 'サージ保護、ノイズフィルタ'
    },
    mountingNotes: 'スライドレール必須。重量のため2人作業推奨。バッテリー交換時の前面アクセス要確保。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'ups-2u',
    name: 'ラックマウントUPS (2U)',
    height: 2,
    depth: 650,
    power: 80,
    heat: 273,
    weight: 75,
    type: 'ups',
    role: 'power-source',
    color: '#EA580C',
    opacity: 30,
    dualPower: false,
    airflow: 'front-to-rear',
    cfm: 140,
    heatGeneration: 273,
    description: '2U高容量無停電電源装置。長時間バックアップと高出力を提供。中規模から大規模機器向け。',
    specifications: {
      capacity: '5000VA/4500W',
      runtime: '約15分（フル負荷時）',
      outlets: 'C13×8, C19×4',
      input: '単相100V 20A',
      battery: 'シールド型鉛蓄電池×2',
      management: 'ネットワーク管理カード対応',
      protection: 'サージ保護、ノイズフィルタ、高調波対策'
    },
    mountingNotes: 'スライドレール必須。重量のため2人作業推奨。バッテリー交換時の前面アクセス要確保。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'ups-4u',
    name: 'ラックマウントUPS (4U)',
    height: 4,
    depth: 700,
    power: 150,
    heat: 512,
    weight: 140,
    type: 'ups',
    role: 'power-source',
    color: '#EA580C',
    opacity: 30,
    dualPower: false,
    airflow: 'front-to-rear',
    cfm: 280,
    heatGeneration: 512,
    description: '4U超高容量無停電電源装置。最長バックアップ時間と最高出力を提供。大規模データセンター向け。',
    specifications: {
      capacity: '10000VA/9000W',
      runtime: '約20分（フル負荷時）',
      outlets: 'C13×12, C19×8',
      input: '単相100V 30A',
      battery: 'シールド型鉛蓄電池×4',
      management: 'ネットワーク管理カード対応',
      protection: 'サージ保護、ノイズフィルタ、高調波対策、絶縁トランス'
    },
    mountingNotes: 'スライドレール必須。重量のため複数人作業必須。バッテリー交換時の前面アクセス要確保。専用ケーブルアーム推奨。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  }
];

// 取り付け部品
export const mountingEquipment: Equipment[] = [
  {
    id: 'cage-nut-m6',
    name: 'ゲージナット M6',
    height: 0,
    depth: 0,
    power: 0,
    heat: 0,
    weight: 0.01,
    type: 'mounting',
    role: 'accessory',
    color: '#6B7280',
    opacity: 30,
    dualPower: false,
    airflow: 'natural',
    cfm: 0,
    heatGeneration: 0,
    description: 'M6ネジ用ゲージナット。ラック柱への機器取り付けに必須。ドラッグでユニットに一括設置。',
    specifications: {
      thread: 'M6×1.0',
      material: '亜鉛メッキ鋼',
      hole: '9.5mm角穴用',
      thickness: '1.2mm',
      package: '50個入り'
    },
    mountingNotes: '事前配置計画必要。取り付け位置正確性重要。',
    nutType: 'm6',
    mountingMethod: 'direct',
    requiresRails: false,
    requiresCageNuts: false
  }
];

// その他機器
export const otherEquipment: Equipment[] = [
  {
    id: 'lcd-console-1u',
    name: 'LCDコンソール (1U)',
    height: 1,
    depth: 650,
    power: 45,
    heat: 154,
    weight: 7,
    type: 'console',
    role: 'monitoring',
    color: '#7C3AED',
    opacity: 30,
    dualPower: false,
    airflow: 'front-to-rear',
    cfm: 20,
    heatGeneration: 154,
    description: 'KVM機能付きLCDコンソール。引き出し式でキーボード・マウス一体型。サーバー管理とメンテナンス作業用。',
    specifications: {
      display: '17インチ TFT液晶',
      resolution: '1280×1024 SXGA',
      kvm: 'PS/2・USB対応',
      ports: '最大16台接続',
      keyboard: '日本語109キー',
      mouse: 'タッチパッド内蔵',
      rail: 'スライドレール付属'
    },
    mountingNotes: 'スライドレール必須。引き出し時の前面スペース要確保。',
    mountingMethod: 'rails',
    requiresRails: true,
    requiresCageNuts: false
  },
  {
    id: 'blank-panel-1u',
    name: 'ブランクパネル (1U)',
    height: 1,
    depth: 50,
    power: 0,
    heat: 0,
    weight: 0.5,
    type: 'panel',
    role: 'accessory',
    color: '#6B7280',
    opacity: 30,
    dualPower: false,
    airflow: 'blocking',
    cfm: 0,
    heatGeneration: 0,
    description: '1U空きユニット封鎖用パネル。エアフロー制御と外観統一のため必須。ゲージナット取り付け。',
    specifications: {
      material: 'アルミ製',
      mounting: 'ゲージナット + M6ネジ固定',
      finish: 'アルマイト処理',
      ventilation: '通気孔なし',
      compliance: 'EIA規格準拠'
    },
    mountingNotes: 'ゲージナット専用。エアフロー遮断効果あり。全空きユニット設置推奨。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'shelf-1u-standard',
    name: '棚板 (標準・1U)',
    height: 1,
    depth: 450,
    power: 0,
    heat: 0,
    weight: 3,
    type: 'shelf',
    role: 'accessory',
    color: '#6B7280',
    opacity: 30,
    dualPower: false,
    airflow: 'natural',
    cfm: 0,
    heatGeneration: 0,
    description: '1U汎用ラック棚板。軽量機器や小型機器の設置用。19インチラック標準対応。ゲージナット取り付け。',
    specifications: {
      material: 'スチール製（粉体塗装）',
      loadCapacity: '20kg',
      mounting: 'ゲージナット + M6ネジ固定（前面・背面）',
      surface: '滑り止め加工',
      compliance: 'EIA規格準拠'
    },
    mountingNotes: 'ゲージナット専用。耐荷重20kg以下の機器用。固定ネジ確実に締付け。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'shelf-1u-vented',
    name: '棚板 (通気孔付き・1U)',
    height: 1,
    depth: 450,
    power: 0,
    heat: 0,
    weight: 2.5,
    type: 'shelf',
    role: 'accessory',
    color: '#6B7280',
    opacity: 30,
    dualPower: false,
    airflow: 'intake',
    cfm: 15,
    heatGeneration: 0,
    description: '1U通気孔付きラック棚板。エアフロー確保が必要な機器用。冷却効率向上。ゲージナット取り付け。',
    specifications: {
      material: 'アルミ製（アルマイト処理）',
      loadCapacity: '15kg',
      ventilation: '通気孔（40%開口率）',
      mounting: 'ゲージナット + M6ネジ固定（前面・背面）',
      airflow: '自然通気対応'
    },
    mountingNotes: 'ゲージナット専用。通気が必要な機器下部に設置。開口部清掃定期実施。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'cable-management-1u',
    name: 'ケーブルマネジメント (1U)',
    height: 1,
    depth: 150,
    power: 0,
    heat: 0,
    weight: 1.5,
    type: 'cable',
    role: 'accessory',
    color: '#6B7280',
    opacity: 30,
    dualPower: false,
    airflow: 'natural',
    cfm: 0,
    heatGeneration: 0,
    description: '1Uケーブル整理パネル。前面にケーブル通し穴とベルクロストラップ付き。ケーブル配線の整理整頓用。',
    specifications: {
      material: 'スチール製（粉体塗装）',
      holes: 'ケーブル通し穴×12',
      accessories: 'ベルクロストラップ×6本',
      mounting: 'ゲージナット + M6ネジ固定',
      compliance: 'EIA規格準拠'
    },
    mountingNotes: 'ゲージナット専用。ケーブル径に応じた穴選択。定期的なケーブル整理推奨。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'cable-management-2u',
    name: 'ケーブルマネジメント (2U)',
    height: 2,
    depth: 200,
    power: 0,
    heat: 0,
    weight: 3,
    type: 'cable',
    role: 'accessory',
    color: '#6B7280',
    opacity: 30,
    dualPower: false,
    airflow: 'natural',
    cfm: 0,
    heatGeneration: 0,
    description: '2U大容量ケーブル整理パネル。多数のケーブル通し穴とケーブルガイド付き。大規模配線向け。',
    specifications: {
      material: 'スチール製（粉体塗装）',
      holes: 'ケーブル通し穴×24',
      accessories: 'ベルクロストラップ×12本、ケーブルガイド×4個',
      mounting: 'ゲージナット + M6ネジ固定',
      compliance: 'EIA規格準拠'
    },
    mountingNotes: 'ゲージナット専用。大容量配線用。ケーブル重量分散に注意。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'cable-tray-1u',
    name: 'ケーブルトレイ (1U)',
    height: 1,
    depth: 300,
    power: 0,
    heat: 0,
    weight: 2,
    type: 'cable',
    role: 'accessory',
    color: '#6B7280',
    opacity: 30,
    dualPower: false,
    airflow: 'natural',
    cfm: 0,
    heatGeneration: 0,
    description: '1Uケーブルトレイ。水平ケーブル配線用。パッチケーブルや電源ケーブルの整理に最適。',
    specifications: {
      material: 'アルミ製（アルマイト処理）',
      capacity: '最大50本（Cat6ケーブル）',
      dividers: '取り外し可能仕切り×3個',
      mounting: 'ゲージナット + M6ネジ固定',
      compliance: 'EIA規格準拠'
    },
    mountingNotes: 'ゲージナット専用。ケーブル重量に注意。仕切りでケーブル種別分離推奨。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'environment-monitor-1u',
    name: '環境監視装置 (1U)',
    height: 1,
    depth: 300,
    power: 25,
    heat: 85,
    weight: 3,
    type: 'monitoring',
    role: 'monitoring',
    color: '#7C3AED',
    opacity: 30,
    dualPower: false,
    airflow: 'natural',
    cfm: 10,
    heatGeneration: 85,
    description: '1U環境監視装置。温度・湿度・煙検知センサー内蔵。SNMP対応でネットワーク監視システムと連携。',
    specifications: {
      sensors: '温度・湿度・煙検知・振動',
      range: '温度:-40～85℃、湿度:0～100%RH',
      accuracy: '温度:±0.5℃、湿度:±3%RH',
      network: 'Ethernet、SNMP v1/v2c/v3',
      alerts: 'Email/SMS/SNMP Trap'
    },
    mountingNotes: 'ゲージナット専用。センサー配置位置要検討。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'kvm-switch-1u',
    name: 'KVMスイッチ (1U)',
    height: 1,
    depth: 400,
    power: 35,
    heat: 119,
    weight: 5,
    type: 'console',
    role: 'monitoring',
    color: '#7C3AED',
    opacity: 30,
    dualPower: false,
    airflow: 'natural',
    cfm: 15,
    heatGeneration: 119,
    description: '1U KVMスイッチ。複数サーバーの集中管理用。デジタル/アナログ両対応。リモートアクセス機能付き。',
    specifications: {
      ports: '最大16台接続',
      interface: 'PS/2・USB・VGA・DVI対応',
      resolution: '最大1920×1200',
      remote: 'IP-KVM対応',
      management: 'Web管理画面'
    },
    mountingNotes: 'ケージナット専用。前面・背面アクセス要確保。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'ntp-server-1u',
    name: '時刻同期サーバー (1U)',
    height: 1,
    depth: 450,
    power: 80,
    heat: 273,
    weight: 8,
    type: 'server',
    role: 'network',
    color: '#7943a8',
    opacity: 30,
    dualPower: true,
    airflow: 'front-to-rear',
    cfm: 25,
    heatGeneration: 273,
    healthStatus: 'normal',
    description: '1U NTPサーバー。GPS対応高精度時刻同期。ネットワーク全体の時刻統一用。Stratum 1対応。',
    specifications: {
      accuracy: '±1マイクロ秒（GPS同期時）',
      gps: 'GPS受信機内蔵',
      ntp: 'NTP v4対応、Stratum 1',
      network: 'Gigabit×2',
      management: 'Web管理画面/SNMP'
    },
    mountingNotes: 'ケージナット専用。GPS アンテナ配線要確保。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'drawer-1u',
    name: '引き出し (1U)',
    height: 1,
    depth: 400,
    power: 0,
    heat: 0,
    weight: 4,
    type: 'other',
    role: 'accessory',
    color: '#7943a8',
    opacity: 30,
    dualPower: false,
    airflow: 'natural',
    cfm: 0,
    heatGeneration: 0,
    description: '1U引き出し。工具や小物の収納用。スライドレール付きで前面からアクセス可能。',
    specifications: {
      capacity: '約5L',
      material: 'スチール製（粉体塗装）',
      rail: 'フルエクステンションレール',
      lock: 'キーロック付き',
      weight: '最大10kg収納可能'
    },
    mountingNotes: 'ゲージナット専用。引き出し時の前面スペース要確保。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  },
  {
    id: 'drawer-2u',
    name: '引き出し (2U)',
    height: 2,
    depth: 450,
    power: 0,
    heat: 0,
    weight: 7,
    type: 'other',
    role: 'accessory',
    color: '#6B7280',
    opacity: 30,
    dualPower: false,
    airflow: 'natural',
    cfm: 0,
    heatGeneration: 0,
    description: '2U大容量引き出し。工具や部品の収納用。仕切り板付きで整理整頓が容易。',
    specifications: {
      capacity: '約12L',
      material: 'スチール製（粉体塗装）',
      rail: 'フルエクステンションレール',
      lock: 'キーロック付き',
      weight: '最大20kg収納可能',
      dividers: '取り外し可能仕切り板×3枚'
    },
    mountingNotes: 'ゲージナット専用。引き出し時の前面スペース要確保。重量のため2人作業推奨。',
    mountingMethod: 'cage-nuts',
    requiresRails: false,
    requiresCageNuts: true
  }
];

// 全機器ライブラリの統合
export const equipmentLibrary: Equipment[] = [
  ...serverEquipment,
  ...networkEquipment,
  ...storageEquipment,
  ...powerEquipment,
  ...mountingEquipment,
  ...otherEquipment
];

// ズームレベル
export const zoomLevels = [75, 100, 125];

// エアフロー方向アイコンマッピング
export const airflowIcons = {
  'front-to-rear': 'ArrowRight',
  'rear-to-front': 'ArrowLeft',
  'side-to-side': 'ArrowUp',
  'intake': 'ArrowDown',
  'exhaust': 'ArrowUp',
  'blocking': 'Square',
  'natural': 'Wind'
};

// 機器タイプアイコンマッピング
export const equipmentTypeIcons = {
  'server': 'Server',
  'network': 'Network',
  'security': 'Shield',
  'storage': 'HardDrive',
  'pdu': 'Zap',
  'ups': 'Zap',
  'power': 'Activity',
  'console': 'Monitor',
  'monitoring': 'Eye',
  'cooling': 'Snowflake',
  'shelf': 'Package',
  'cable': 'Cable',
  'mounting': 'Wrench',
  'rail': 'Move',
  'panel': 'Square',
  'other': 'Settings'
};